# Site settings
name: PandaDL
email: duimu@qq.com
author: duimu
url: http://www.pandadl.com
baseurl: ''
description: 
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: duimu

# Build settings
markdown: kramdown

baidu_analysis: 