# Site settings
name: Sightthink
email: duimu@qq.com
author: duimu
url: http://www.sightthink.com
baseurl: ''
description: think what in your sight!
meta_description: 
motto: 卓识所以远见
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: duimu

# Build settings
markdown: kramdown

baidu_analysis: 